// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxJPvTgBazd5BmqCCvS-FtmdedAFhlU8',
    appId: '1:898577908366:web:e169c1b0eee512e8d87fdf',
    messagingSenderId: '898577908366',
    projectId: 'plant-shop-417',
    authDomain: 'plant-shop-417.firebaseapp.com',
    storageBucket: 'plant-shop-417.appspot.com',
    measurementId: 'G-HB90EZ1G4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP-Xlkgs3Xx-SheAT9KghuiCWAl9m7eCA',
    appId: '1:898577908366:android:1c2c94db543a89e4d87fdf',
    messagingSenderId: '898577908366',
    projectId: 'plant-shop-417',
    storageBucket: 'plant-shop-417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZvPpplMThb510NXg8wBBuy5lsFJYjfVw',
    appId: '1:898577908366:ios:7369c4d29df440bdd87fdf',
    messagingSenderId: '898577908366',
    projectId: 'plant-shop-417',
    storageBucket: 'plant-shop-417.appspot.com',
    iosBundleId: 'com.example.flutterPlantsappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZvPpplMThb510NXg8wBBuy5lsFJYjfVw',
    appId: '1:898577908366:ios:32a57ed6e57368e6d87fdf',
    messagingSenderId: '898577908366',
    projectId: 'plant-shop-417',
    storageBucket: 'plant-shop-417.appspot.com',
    iosBundleId: 'com.example.flutterPlantsappProject.RunnerTests',
  );
}
